# Included paths
included:
  - Source
  - Shuffle Trip

# Excluded paths
excluded:
  - Carthage
  - Pods


# Opt-in rules
opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - array_init
  - closure_end_indentation
  - closure_spacing
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - collection_alignment
  - discouraged_none_name
  - discouraged_optional_boolean
  - empty_count
  - expiring_todo
  - explicit_init
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - indentation_width
  - inert_defer
  - last_where
  - line_length
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - period_spacing
  - sorted_imports
  - static_operator
  - toggle_bool
  

# Rules
line_length:
  warning: 250
  error: 325

trailing_semicolon: error

force_cast: warning

function_parameter_count:
  warning: 5

# Disabled rules
disabled_rules:
  - identifier_name
  - statement_position
  - trailing_whitespace
  - void_function_in_ternary
  - todo